# Generated by Django 6.0.2 on 2026-02-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='faixa_etaria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
