# Generated by Django 6.0.2 on 2026-02-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_category_faixa_etaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='faixa_etaria',
        ),
    ]
